//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duble2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_has_Tasks
    {
        public int Student_NumberOfCreditBook { get; set; }
        public int Tasks_idTaskNumber { get; set; }
        public Nullable<System.DateTime> TaskPassDate { get; set; }
        public Nullable<System.DateTime> TaskGetDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
